### PR TITLE
Fix PrometheusRule issue

### LINKED ISSUE #213: PrometheusRule invalid alert configuration shouldn't block other alerts
When applying a PrometheusRule with multiple alerts, if one of the alerts is misconfigured, the whole PrometheusRule reconciliation is stopped and the remaining alerts are not created, even if they are valid. The operator should block the creation of the invalid alerts only, and allow other alerts to be created.

### PR DESCRIPTION
**Pull request by assafad1**
Fixes #213

### CODE REVIEW

File: internal/controller/prometheusrule_controller.go [hunk 1]
```diff
@@ -174,6 +174,7 @@ func (r *PrometheusRuleReconciler) convertPrometheusRuleAlertToCxAlert(ctx conte
 	}
 
 	alertsToKeep := make(map[string]bool)
+	var errorsEncountered []error
```
Comment (OrNovo) [inline internal/controller/prometheusrule_controller.go:177]: Consider using [errors](https://pkg.go.dev/errors) instead

**Review by OrNovo — APPROVED** [review]
